### ISSUE TITLE
Can't add multiple Nextcloud accounts

### ISSUE THREAD

**Issue by youbzh** [ONLYOFFICE/documents-app-ios#163]
Version 7.5 on iPadOS 15.7.2
I can only add one Nextcloud account. I can start the process of adding the second account, once it's done and everything is validated, the account doesn't appear.
Thank you!

**Comment by yuvachevaalex** [comment]
Hello, @youbzh 
Thanks for your request!
I confirm that this is a bug. I registered it with number 66885 in our issue tracker.

**Comment by ayuzhin** [comment]
Fixed https://github.com/ONLYOFFICE/documents-app-ios/pull/256
